name: 'Emanates Deploy'

on:
  issues:
    types: [opened, edited, deleted]

jobs:
  # Deploy to Netlify
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Set the repo env variable
        run: echo "REPO=$(echo $GITHUB_REPOSITORY)" >> $GITHUB_ENV
      - name: Build the static page
        run: npm run generate
        env:
          EMANATES_TOKEN: ${{ secrets.EMANATES_TOKEN }}
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.EMANATES_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
